package api

object ServerValues{
    const val METHOD_MODERATE_CONTENT = "moderate-content"
    const val METHOD_CREATE_TEST_USER = "create-test-user"
    const val METHOD_GET_UID_BY_PLAIN_PHONE = "get-uid-by-plain-phone"
    const val METHOD_GET_DOCUMENT = "get-document"
    const val METHOD_SET_USER_AGE = "set-user-age"
    const val METHOD_SET_USER_FCM_TOKEN = "set-user-fcm-token"
    const val METHOD_SET_USER_FACEBOOK_DATA = "set-user-fb-data"
    const val METHOD_SET_IP = "set-ip"
    const val METHOD_GET_MY_CAMPAIGN = "get-my-campaign"
    const val METHOD_ARCHIVE_FEED_ITEM = "archive-feed-item"
    const val METHOD_UNARCHIVE_FEED_ITEM = "unarchive-feed-item"
    const val METHOD_CREATE_COMMENT= "create-comment"
    const val METHOD_BLOCK_USER = "block-user"
    const val METHOD_UNBLOCK_USER = "unblock-user"
    const val METHOD_CREATE_COMPLAINT = "create-complaint"
    const val METHOD_CREATE_SMS_INVITES = "create-sms-invites"
    const val METHOD_SET_CONTACTS = "set-contacts"
    const val METHOD_SET_CONTACTS_FOR_ADS = "set-contacts-for-ads"
    const val METHOD_ACKNOWLEDGE_COMMENT_REJECTION = "acknowledge-comments-rejection"
    const val METHOD_ACKNOWLEDGE_DM_REJECTION = "acknowledge-direct-messages-rejection"
    const val METHOD_CREATE_DIRECT_MESSAGE = "create-direct-message"
    const val METHOD_CREATE_APP_REVIEW = "create-app-review"
    const val METHOD_MUTE_FEED_ITEM = "mute-feed-item"
    const val METHOD_UNMUTE_FEED_ITEM = "unmute-feed-item"
    const val METHOD_SET_POST_TAG = "set-post-tag"
    const val METHOD_DELETE_COMMENT = "delete-comment"
    const val METHOD_SET_USER_LAST_SESSION = "set-user-last-session"
    const val METHOD_UNSUSPEND_USER = "unsuspend-user"
    const val METHOD_INIT_FEED = "init-feed"
    const val METHOD_DELETE_DIRECT_MESSAGE = "delete-direct-message"
    const val METHOD_GET_RATING_PROMPTNESS = "get-rating-promptness"
    const val METHOD_SET_CHAT_TITLE = "set-chat-title"
    const val METHOD_DELETE_USER = "delete-user"
    const val METHOD_GET_CHAT_PARTICIPANTS = "get-chat-participants"

    // JSON server fields
    const val FIELD_UID = "uid"
    const val FIELD_PASSWORD = "password"
    const val FIELD_CONTENT_ID = "contentId"
    const val FIELD_CONTENT_TYPE = "contentType"
    const val FIELD_DECISION = "decision"
    const val FIELD_NOTES = "notes"
    const val FIELD_REJECTION_REASON = "rejectionReason"
    const val FIELD_REJECTION_SEVERITY = "rejectionSeverity"
    const val FIELD_DECISIONS = "decisions"
    const val FIELD_TEST_USER_PHONE_NUMBER = "phone_number"
    const val FIELD_API_KEY_FOR_USER_CREATION = "api_key"
    const val FIELD_API_KEY_FOR_GETTING_DOCUMENT = "apiKey"
    const val FIELD_JWT = "jwt"
    const val FIELD_PHONE_NUMBER = "phoneNumber"
    const val FIELD_PHONE_NUMBERS = "phoneNumbers"
    const val FIELD_COLLECTION_NAME = "collectionName"
    const val FIELD_DOCUMENT_ID = "documentId"
    const val FIELD_AGE = "age"
    const val FIELD_FCM_TOKEN = "fcmToken"
    const val FIELD_FB_USER_ID = "fbUserId"
    const val FIELD_FB_ACCESS_TOKEN = "fbAccessToken"
    const val FIELD_FEED_ITEM_ID = "feedItemId"
    const val FIELD_TEXT = "text"
    const val FIELD_AUTHOR_NAME = "authorName"
    const val FIELD_CHAT_ID = "chatId"
    const val FIELD_POST_ID = "postId"
    const val FIELD_SHORT_TEXT = "shortText"
    const val FIELD_ITEM_ID = "itemId"
    const val FIELD_ITEM_TYPE = "itemType"
    const val FIELD_CAUSE = "cause"
    const val FIELD_INVITES = "invites"
    const val FIELD_CONTACTS = "contacts"
    const val FIELD_EMAILS = "emails"
    const val FIELD_COMMENT_ID = "commentId"
    const val FIELD_COMMENT_IDS = "commentIds"
    const val FIELD_DIRECT_MESSAGE_IDS = "directMessageIds"
    const val FIELD_PEER_NAME= "peerName"
    const val FIELD_PARENT_CHAT_ID = "parentChatId"
    const val FIELD_SCORE = "score"
    const val FIELD_TAG = "tag"
    const val FIELD_TARGET_USER_ID = "targetUserId"
    const val FIELD_MESSAGE_ID = "messageId"
    const val FIELD_ALGO = "algo"

    // Firestore collections names
    const val COLLECTION_NAME_USERS = "users"
    const val COLLECTION_NAME_COMMENTS = "comments"
    const val COLLECTION_NAME_FEED = "feed"
    const val COLLECTION_NAME_TEST_FCM_NOTIFICATIONS = "testFcmNotifications"

    // Firestore fields value
    const val VALUE_STATE_NEVER_MUTED = "neverUnmuted"
    const val FIELD_LAST_SESSION_AT_UTC = "lastSessionAtUtc"

    // Enums server values.
    const val MESSAGE_TYPE_COMMENT = "comment"
    const val MESSAGE_TYPE_DIRECT_MESSAGE = "directMessage"

    const val POST_TAG_SELF_DISCLOSURE = "selfDisclosure"
    const val POST_TAG_QUESTION_PROMPT = "questionPrompt"
    const val POST_TAG_OTHER_HIGH = "otherHigh"
    const val POST_TAG_GREETING = "greeting"
    const val POST_TAG_APP_QUESTION = "appQuestion"
    const val POST_TAG_SEX_CHAT = "sexChat"
    const val POST_TAG_OTHER_LOW = "otherLow"

    const val MODERATION_DECISION_TYPE_APPROVED = "approved"
    const val MODERATION_DECISION_TYPE_REJECTED = "rejected"

    const val MODERATION_REJECTION_SEVERITY_LOW = "low"
    const val MODERATION_REJECTION_SEVERITY_MIDDLE = "middle"
    const val MODERATION_REJECTION_SEVERITY_HIGH = "high"

    const val NOTES_NONE = "none"
    const val NOTES_SOME_NOTE = "Some note"
    const val NOTES_NO_PUSH = "noPushInMutedDmChatVerification"
    const val REJECTION_REASON = "Other"
    const val REJECTION_SEVERENITY = "low"

    const val FIELD_PAGE_SIZE = "pageSize"
    const val FIELD_PAGE_CURSOR = "pageCursor"
    const val METHOD_GET_SUGGESTED_CHATS = "get-suggested-chats"
    const val METHOD_FOLLOW_SUGGESTED_CHAT = "follow-suggested-chat"

}